### PR TITLE
Update README to call out demo and product overview before getting in…

### PR DESCRIPTION
**Pull request by kevinrobinson**
…to technical details

@alexsoble What do you think, is this too much introduction?  It feels nice to have the demo, purpose and product overview right up front for curious citizens and potential contributors, say from Code For Boston.  Alternately we could move this to the `studentinsights.org` landing page, cut the copy out here and link to that.

?que piensas?

### CODE REVIEW

**Comment by kevinrobinson** [comment]
Also adds a note for https://github.com/codeforamerica/somerville-teacher-tool/issues/415

**Comment by kevinrobinson** [comment]
This was primarily intended to address https://github.com/codeforamerica/somerville-teacher-tool/issues/414

**Comment by alexsoble** [comment]
:+1: 

Looks great!

I think updating the landing page is a separate issue. For the landing page we want a "Hello World" type overview. The summary you wrote up fits well in the README because it's a more detailed feature-by-feature guide for someone who's not familiar with the project.

**Comment by kevinrobinson** [comment]
cool, sounds good, thanks!

**Pull request merged**
