### PR TITLE
Dockerize Rails and Postgres for local development

### PR DESCRIPTION
**Pull request by kevinrobinson**
@alexsoble I started hacking on this a bit and setting up my development environment.  I worked on two infrastructure-y pieces that I think might be helpful, which I'll submit as separate PRs.  Let me know what you think! :)

Instead of installing Postgres, etc. on my local laptop, I worked to add support for running the project in Docker containers for local development.  The only change to the existing setup is upping the Ruby version to 2.2.3, only because there isn't a supported Ruby container for 2.1.6.

This adds a `Dockerfile` that can run the Rails app in a container, and also adds a `docker-compose.yml` file that pulls in the standard Postgres container and connects the two together.  So for workflow, running `docker-compose up` starts ephemeral Rails and Postgres containers that are linked together, and hitting `http://docker:3000` works just like it does when running everything locally.  Possibly be useful for production deployments at some point.

### CODE REVIEW

**Comment by alexsoble** [comment]
@kevinrobinson: If it makes it easier to fork & start hacking on Student Insights I'm all for it!

I pulled down this branch and started working on setting up local Docker development. Wasn't able to get it running the first try but will keep at it.

About the production idea — I think it's worth exploring. Crucial input will come from the Somerville schools IT team, John Breslin and Bryant Brown, since they will be managing app deployment.

**Comment by kevinrobinson** [comment]
@alex Cool, sounds good!  If you want to paste any problems you had in the setup I can maybe help debug.

FWIW, I've been hacking on manually getting the project running on containers in EC2, and this is working albeit with a bunch of unfinished pieces, so we can chat Friday and see where it's at.  Again, that's mostly from just me experimenting and I'm definitely not suggesting it's worth spending time on trying to do for realz without input for John and Bryant.  More just sharing some side-hacking. :)

**Comment by alexsoble** [comment]
@kevinrobinson Sounds good!

**Comment by kevinrobinson** [comment]
Added a commit with notes about using `docker-machine-nfs`, see https://github.com/codeforamerica/somerville-teacher-tool/pull/336#issuecomment-158441877 for more info.

**Comment by alexsoble** [comment]
Got this running locally on my machine — fantastic improvement! The docker flow looks like a far more streamlined way for other developers to set up the project and contribute. 

Thanks @kevinrobinson!

**Comment by kevinrobinson** [comment]
no prob!

**Pull request merged**
