### PR TITLE
Added the roster_url to the controller and mapped it to the path of t…

### PR DESCRIPTION
**Pull request by griggsca91**
Set the StudentsController roster_url to the path of the student's homeroom so the roster_url will point to the correct homeroom instead of just the front page.  This fix is referencing https://github.com/codeforamerica/somerville-teacher-tool/issues/159

### CODE REVIEW

**Comment by griggsca91** [comment]
whoops didn't test the build, nvm.

**Comment by alexsoble** [comment]
@griggsca91 — This is a great pull request! 

To update the tests, let's give our default FactoryGirl-generated student a homeroom.  That way the student will have a defined roster_url.  Add a homeroom association to `factory :student` on line 9...

```
      association :homeroom
```
 
...and the tests will pass. Once you add that we're good to merge! 

Thanks for your contribution Christian!

**Comment by griggsca91** [comment]
Thanks, and added.  And yeah no problem!

**Comment by alexsoble** [comment]
@griggsca91 — Merged! Are you a member of Code for SF or Code for Boston by any chance?

**Comment by griggsca91** [comment]
@alexsoble - Code for Boston.  I went to my first meeting last week and met Chad there.  Thought it was interesting and I could help out with this in my free time.

**Comment by alexsoble** [comment]
@griggsca91 — Awesome! We'll be there tonight, see you there?

**Comment by griggsca91** [comment]
Cool! Yep, I'll be there.

**Pull request merged**
