### PR TITLE
Overlay data on student profile graph #119

### PR DESCRIPTION
**Pull request by civerson**
[Review](https://codenvy.com/f?id=5t8pd196sslsuuu2)

This is the initial front-end work, assessment data code will come next.

### CODE REVIEW

**Comment by alexsoble** [comment]
Hi @civerson, thanks for the pull request!

I took a look at the Review in IDE option but the requested permissions from GitHub made me pause:

requested-permissions

So I went ahead, cloned the project, and made a GIF of the multiselect flow:

civerson-pull

I think the multiselect works really smooth. I want to hear thoughts from @marimuraki and @AmirHadjihabib as well. One of the visualization topics we were discussing involved comparisons. It makes sense to compare attendance events and behavior events on the same graph because they are both counts. But does it make sense to also show percentile-based values like MCAS and STAR growth levels on the same graph? Open question.

**Comment by marimuraki** [comment]
@civerson Thank you for working on this feature! And @alexsoble thanks for putting up a GIF here (I paused too when I got to the Codenvy login so didn't see this until now).

I like how the multi-select in the **student profile graph** is consistent to how teachers would use selection of indicators to include in the **student roster table**. It makes the experience easier / simpler to not have to figure out too many different moving pieces. @AmirHadjihabib: design-wise, what do you think?

As @alexsoble, we still need to think about how to best graph multiple indicators which are of different scale. Idea I thought of immediately when the teachers asked for this was to do correlation graphs with indicators on two different axes ... but this might be too complicated and might make sense only to the more data-savvy. Or, we can restrict the graphs to only be able to graph like items (e.g., scores with scores, growth percentiles with growth percentiles, counts with counts, etc) but this sort of defeats the purpose that Sam (5th grade ELA/math teacher) wanted of comparing **behavior vs. assessment**. 

It's definitely an open question to think more deeply about.

**Comment by civerson** [comment]
Hi @alexsoble, You can ignore that codenvy project file for the merge. That file and button you see on Github is just for the convenience of Codenvy users, like me. 

@marimuraki, good point on the scale for this chart, visualizing trends over time can sometimes be misleading with different scales. For example growth is already indicated by direction of the trend line. In particular, MCAS Growth Percentile is tracking student scores from one year to the next and reporting a percentile, which speaks to the distribution. We may want raw assessment data or at least percentile (without built in growth) for this visualization, if we can get it. I look forward to the feature ideas that come out of this.

**Comment by alexsoble** [comment]
@civerson: We owe you clearer specs here! In retrospect, I was too quick to slap `help wanted` on this since we haven't fully figured out the product direction we want to take. I apologize for that. I'm going to close this PR for now and re-open once we have a clearer direction — very much appreciate the contribution and again, apologies!

**Pull request closed without merging**
